title: Stadtbibliothek Köln & P2PU
description: 'Lernteams - eine neuartige Lernmethode in der Stadtbibliothek Köln


  Schließen Sie sich mit anderen Interessierten in der Bibliothek zu einer kleinen
  Lerngruppe zusammen, um gemeinsam einen Online-Kurs zu absolvieren! Die moderierten
  Lernteams treffen sich einmal pro Woche für 6 bis 8 Wochen und können kostenlos
  besucht werden.'
language: de
