title: Stadtbibliothek Köln & P2PU
description: 'Lernteams - gemeinsam mit- und voneinander lernen


  Sie möchten ein neues Wissensgebiet erkunden, dies aber nicht alleine, sondern
  gemeinsam mit anderen Interessierten? Erleben Sie E-Learning mal anders, indem
  Sie sich mit Gleichgesinnten in einem Lernteam vor Ort oder online zu einem
  bestimmten Thema wöchentlich treffen und austauschen. Die Kursdauer richtet
  sich nach dem jeweiligen Thema und die Treffen werden von geschulten Mitarbeitenden
  koordiniert und moderiert.'
language: de
